name: Manual job to trigger
on:
  workflow_dispatch:
    inputs:
      appEnvironment:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
        - qa
        - pro

      releaseType:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
        - major
        - minor
        - patch

      
      isOnlyDatabase:
        description: 'Only update database'
        required: false
        type: boolean

      tags:
        description: 'QA environment'
        required: false
        default: 'qa'
        # pro feature
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true

jobs:
  log-the-inputs:
    runs-on: [self-hosted]
    steps:
      - run: |
          echo "Release Type: $RELEASE_TYPE"
          echo "Only database: $ONLY_DATABASE"
          echo "Environment: $ENVIRONMENT"
        env:
          RELEASE_TYPE: ${{ inputs.releaseType }}
          ENVIRONMENT: ${{ inputs.appEnvironment }}
          ONLY_DATABASE: ${{ inputs.isOnlyDatabase }}